-- Create storage buckets for images and 3D models

-- Images bucket (for uploaded photos)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'images',
    'images',
    true,
    10485760, -- 10MB limit
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
);

-- Models bucket (for generated 3D models)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'models',
    'models',
    true,
    104857600, -- 100MB limit for 3D models
    ARRAY['model/gltf-binary', 'model/gltf+json', 'application/octet-stream']
);

-- Storage policies for images bucket

-- Anyone can upload images
CREATE POLICY "Anyone can upload images"
    ON storage.objects FOR INSERT
    WITH CHECK (bucket_id = 'images');

-- Anyone can view images (public bucket)
CREATE POLICY "Anyone can view images"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'images');

-- Users can delete their own images (based on path pattern: user_id/filename)
CREATE POLICY "Users can delete own images"
    ON storage.objects FOR DELETE
    USING (
        bucket_id = 'images' 
        AND (auth.uid()::text = (storage.foldername(name))[1] OR auth.uid() IS NULL)
    );

-- Storage policies for models bucket

-- Only service role can upload models (generated by backend)
CREATE POLICY "Service role can upload models"
    ON storage.objects FOR INSERT
    WITH CHECK (bucket_id = 'models');

-- Anyone can view/download models (public bucket)
CREATE POLICY "Anyone can view models"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'models');

-- Users can delete models associated with their uploads
CREATE POLICY "Users can delete own models"
    ON storage.objects FOR DELETE
    USING (
        bucket_id = 'models'
        AND (auth.uid()::text = (storage.foldername(name))[1] OR auth.uid() IS NULL)
    );
